language: python

python:
    - 3.7
    - 3.8

install:
    - pip install -r requirements.txt

script:
    pytest --cov-report term --cov=spiralsort/

after_success:
    - bash <(curl https://codecov.io/bash)
